<<<<<<< HEAD
nodeLinker: node-modules
=======
compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.8.1.cjs
>>>>>>> 2ed0fdee0936456c23c949bfb25ac5ec9c563e38
